version: '3.9'
services:
  app:
    container_name: trolly
    build:
      context: ../..
      dockerfile: ./devops/docker/Dockerfile
    restart: always
    ports:
      - 4000:4000
      - 80:80
      - 443:443
    command: ["-env", "production", "-dsn", "trolly:secret_trolly_password@tcp(db)/trolly?parseTime=true"]
    volumes:
      - certs:/certs
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: trolly_db
    image: jsurf/rpi-mariadb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=trolly
      - MYSQL_PASSWORD=secret_trolly_password
      - MYSQL_DATABASE=trolly
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    volumes:
      - trolly_db:/var/lib/mysql
volumes:
  trolly_db:
  certs: